### ISSUE TITLE
Create options for distro configuration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix-generator#111]
One of the starting points for the development of the Meilix Generator was the labs issue https://github.com/fossasia/labs.fossasia.org/issues/135. We can now follow up here. Please create subissues for open items.

- [x] Use LXQT (Issue #??)
- [ ]  Switch off notifications
- [ ]  Switch off screensaver and sleep modus 
- [ ]  Switch off system sounds (https://github.com/fossasia/meilix/pull/112)
- [x] disable bookmarks in browser (Issue #??)
- [ ] Install ownCloud/NextCloud client
-https://download.owncloud.org/download/repositories/stable/owncloud/
- [x]  install Dropbox
- [ ]  Pre-set start system without password (DONE, happens in live image)
- [ ]  install Gtalk/Hangout
  - unofficial app yakyak 
  - chromium extension app
  - pidgin messenger configured for hangout (only chatting not video/calling)
  - ".desktop" file which opens a browser which supports hangout on the hangout page in /usr/share/applications
- [ ]  install Firefox (Issue #??) 
- [ ] Chromium
- [ ]  set Chromium as default
- [x]  set custom start page and set "re-start with last opened tabs" (in case laptop is crashing)
- [x]  install git (Issue #??)
- [ ]  change desktop background with custom image
- [ ]  update to latest version (without password)
  - [X] sudo apt-get update happens to the system before the ISO is created
- [ ]  switch off screen dimming (https://github.com/fossasia/meilix/pull/113)
- [ ]  switch off power management saving features (https://github.com/fossasia/meilix/pull/110)
- [ ]  link to the slide folder from the desktop (edit "make a link")
- [x]  authide panel (Issue #??)(https://github.com/fossasia/meilix/pull/109)
- [ ]  install local language keyboard layouts
  - might be a user configuration
  - There are a limited number of keyboards, same like with packages
  - all keyboards are preinstalled
  - there is a menu somewhere which may only appear if you as a user can choose between several languages. There, these languages should appear
  - TODO: Create an issue for this
- [x]  install VLC
- [ ] VLC  set as standard video player
- [x]  install LibreOffice, Gimp, Inkscape
- [x]  set search engine
- [ ]  distro referrals: Amazon Referral link: When someone buys on ISO, supports This iso

Discard:
- [ ] install chrome (https://github.com/fossasia/meilix/issues/117)
