### ISSUE TITLE
How can we onboard new developers to the project?

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#80]
We have our project going and developing in a smooth way. The thing we need now is to introduce the project to people out there and asked them to give it a try. We also want to engage more and more onboard developers in the project.
Ways to go for it:
- [ ] Maketize project to developers
- [ ] New kind of project: OS by configuration and one can develop its own iso for personal use without a single line to code with the simple GUI.
- [ ] (REF1)Tag an issue and add it to a platform for new developers (first-timers-only issues: they are first-time open-source contributors)
      https://github.com/search?utf8=%E2%9C%93&q=state%3Aopen+label%3A%22first-timers-only%22&type=Issues
- [ ] http://firstpr.me/ <- about issue
- [ ] http://up-for-grabs.net/#/

**Comment by meets2tarun** [comment]
https://github.com/blog/2397-making-it-easier-to-grow-communities-on-github

**Comment by tabesin** [comment]
Screenrecordings? https://askubuntu.com/questions/4428/how-can-i-record-my-screen

**Comment by abishekvashok** [comment]
> Maketize project to developers

What do you mean by this?

**Comment by tabesin** [comment]
I think it is important to add such existing documentation to the repo.

**Comment by amansheaven** [comment]
I can work on a good presentation @meets2tarun. All I would need is a layout to work on.

**Comment by meets2tarun** [comment]
@amansheaven 
Go for it with your own layout.
Lemme know if you need any help.

**Comment by amansheaven** [comment]
Sure sir, I'll make some layout about the use of generator. Maybe you can help me with some facts and things which makes the generator stand out.
@meets2tarun

**Comment by meets2tarun** [comment]
Generators special features are explicitly mention in the readme.
Do have a look.
You can come with a primitive model, then we can discuss what improvements we can make into it.
@amansheaven

**Comment by amansheaven** [comment]
https://docs.google.com/presentation/d/1nJEBlQ7XT__CkvdqA8egI7Zt7DvtbYwb5ok7wX5Uiko/edit?usp=sharing

Sorry for so much of a delay (cause of my university exams), I started working on a user centric presentation please take a look and comment...

**Comment by meets2tarun** [comment]
@amansheaven 
Seems interesting, 
curious to see more progress.

Good Luck!!

**Comment by amansheaven** [comment]
Apart from the presentation, I think a animated small video with some toons at description would also look lucrative, In addition we can write description in a user friendly manner which can also appeal users. It's proven that a better presentation leads to people using/ trying out the product.
*guilty psychology fan*

After a basic ppt shall I work on the description?? @meets2tarun

**Comment by xeon-zolt** [comment]
@amansheaven https://eventyay.com/e/423d0650 come to this event lets discuss more

**Comment by amansheaven** [comment]
sure sir @xeon-zolt ill brew some samples too just in case you want to try them on...
